/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var repo_common$types_pb = require('../repo/common-types_pb.js');
var api_pb = require('../api_pb.js');
goog.exportSymbol('proto.listenfield.repo.QueryTimeScopeResult', null, global);
goog.exportSymbol('proto.listenfield.repo.UpsertTimeScopeRequest', null, global);
goog.exportSymbol('proto.listenfield.repo.UpsertTimeScopeResult', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.listenfield.repo.UpsertTimeScopeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.listenfield.repo.UpsertTimeScopeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.listenfield.repo.UpsertTimeScopeRequest.displayName = 'proto.listenfield.repo.UpsertTimeScopeRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.listenfield.repo.UpsertTimeScopeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.listenfield.repo.UpsertTimeScopeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.listenfield.repo.UpsertTimeScopeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.listenfield.repo.UpsertTimeScopeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    item: (f = msg.getItem()) && repo_common$types_pb.TimeScope.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.listenfield.repo.UpsertTimeScopeRequest}
 */
proto.listenfield.repo.UpsertTimeScopeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.listenfield.repo.UpsertTimeScopeRequest;
  return proto.listenfield.repo.UpsertTimeScopeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.listenfield.repo.UpsertTimeScopeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.listenfield.repo.UpsertTimeScopeRequest}
 */
proto.listenfield.repo.UpsertTimeScopeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new repo_common$types_pb.TimeScope;
      reader.readMessage(value,repo_common$types_pb.TimeScope.deserializeBinaryFromReader);
      msg.setItem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.listenfield.repo.UpsertTimeScopeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.listenfield.repo.UpsertTimeScopeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.listenfield.repo.UpsertTimeScopeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.listenfield.repo.UpsertTimeScopeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItem();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      repo_common$types_pb.TimeScope.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.TimeScope item = 1;
 * @return {?proto.listenfield.repo.common.TimeScope}
 */
proto.listenfield.repo.UpsertTimeScopeRequest.prototype.getItem = function() {
  return /** @type{?proto.listenfield.repo.common.TimeScope} */ (
    jspb.Message.getWrapperField(this, repo_common$types_pb.TimeScope, 1));
};


/** @param {?proto.listenfield.repo.common.TimeScope|undefined} value */
proto.listenfield.repo.UpsertTimeScopeRequest.prototype.setItem = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.listenfield.repo.UpsertTimeScopeRequest.prototype.clearItem = function() {
  this.setItem(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.listenfield.repo.UpsertTimeScopeRequest.prototype.hasItem = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.listenfield.repo.UpsertTimeScopeResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.listenfield.repo.UpsertTimeScopeResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.listenfield.repo.UpsertTimeScopeResult.displayName = 'proto.listenfield.repo.UpsertTimeScopeResult';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.listenfield.repo.UpsertTimeScopeResult.prototype.toObject = function(opt_includeInstance) {
  return proto.listenfield.repo.UpsertTimeScopeResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.listenfield.repo.UpsertTimeScopeResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.listenfield.repo.UpsertTimeScopeResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    item: (f = msg.getItem()) && repo_common$types_pb.TimeScope.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.listenfield.repo.UpsertTimeScopeResult}
 */
proto.listenfield.repo.UpsertTimeScopeResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.listenfield.repo.UpsertTimeScopeResult;
  return proto.listenfield.repo.UpsertTimeScopeResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.listenfield.repo.UpsertTimeScopeResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.listenfield.repo.UpsertTimeScopeResult}
 */
proto.listenfield.repo.UpsertTimeScopeResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new repo_common$types_pb.TimeScope;
      reader.readMessage(value,repo_common$types_pb.TimeScope.deserializeBinaryFromReader);
      msg.setItem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.listenfield.repo.UpsertTimeScopeResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.listenfield.repo.UpsertTimeScopeResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.listenfield.repo.UpsertTimeScopeResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.listenfield.repo.UpsertTimeScopeResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItem();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      repo_common$types_pb.TimeScope.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.TimeScope item = 1;
 * @return {?proto.listenfield.repo.common.TimeScope}
 */
proto.listenfield.repo.UpsertTimeScopeResult.prototype.getItem = function() {
  return /** @type{?proto.listenfield.repo.common.TimeScope} */ (
    jspb.Message.getWrapperField(this, repo_common$types_pb.TimeScope, 1));
};


/** @param {?proto.listenfield.repo.common.TimeScope|undefined} value */
proto.listenfield.repo.UpsertTimeScopeResult.prototype.setItem = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.listenfield.repo.UpsertTimeScopeResult.prototype.clearItem = function() {
  this.setItem(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.listenfield.repo.UpsertTimeScopeResult.prototype.hasItem = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.listenfield.repo.QueryTimeScopeResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.listenfield.repo.QueryTimeScopeResult.oneofGroups_);
};
goog.inherits(proto.listenfield.repo.QueryTimeScopeResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.listenfield.repo.QueryTimeScopeResult.displayName = 'proto.listenfield.repo.QueryTimeScopeResult';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.listenfield.repo.QueryTimeScopeResult.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.listenfield.repo.QueryTimeScopeResult.QueryResOneofCase = {
  QUERY_RES_ONEOF_NOT_SET: 0,
  ITEM: 1,
  QUERYMETA: 2
};

/**
 * @return {proto.listenfield.repo.QueryTimeScopeResult.QueryResOneofCase}
 */
proto.listenfield.repo.QueryTimeScopeResult.prototype.getQueryResOneofCase = function() {
  return /** @type {proto.listenfield.repo.QueryTimeScopeResult.QueryResOneofCase} */(jspb.Message.computeOneofCase(this, proto.listenfield.repo.QueryTimeScopeResult.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.listenfield.repo.QueryTimeScopeResult.prototype.toObject = function(opt_includeInstance) {
  return proto.listenfield.repo.QueryTimeScopeResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.listenfield.repo.QueryTimeScopeResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.listenfield.repo.QueryTimeScopeResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    item: (f = msg.getItem()) && repo_common$types_pb.TimeScope.toObject(includeInstance, f),
    querymeta: (f = msg.getQuerymeta()) && api_pb.BatchedQueryMetadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.listenfield.repo.QueryTimeScopeResult}
 */
proto.listenfield.repo.QueryTimeScopeResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.listenfield.repo.QueryTimeScopeResult;
  return proto.listenfield.repo.QueryTimeScopeResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.listenfield.repo.QueryTimeScopeResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.listenfield.repo.QueryTimeScopeResult}
 */
proto.listenfield.repo.QueryTimeScopeResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new repo_common$types_pb.TimeScope;
      reader.readMessage(value,repo_common$types_pb.TimeScope.deserializeBinaryFromReader);
      msg.setItem(value);
      break;
    case 2:
      var value = new api_pb.BatchedQueryMetadata;
      reader.readMessage(value,api_pb.BatchedQueryMetadata.deserializeBinaryFromReader);
      msg.setQuerymeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.listenfield.repo.QueryTimeScopeResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.listenfield.repo.QueryTimeScopeResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.listenfield.repo.QueryTimeScopeResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.listenfield.repo.QueryTimeScopeResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItem();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      repo_common$types_pb.TimeScope.serializeBinaryToWriter
    );
  }
  f = message.getQuerymeta();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      api_pb.BatchedQueryMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional common.TimeScope item = 1;
 * @return {?proto.listenfield.repo.common.TimeScope}
 */
proto.listenfield.repo.QueryTimeScopeResult.prototype.getItem = function() {
  return /** @type{?proto.listenfield.repo.common.TimeScope} */ (
    jspb.Message.getWrapperField(this, repo_common$types_pb.TimeScope, 1));
};


/** @param {?proto.listenfield.repo.common.TimeScope|undefined} value */
proto.listenfield.repo.QueryTimeScopeResult.prototype.setItem = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.listenfield.repo.QueryTimeScopeResult.oneofGroups_[0], value);
};


proto.listenfield.repo.QueryTimeScopeResult.prototype.clearItem = function() {
  this.setItem(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.listenfield.repo.QueryTimeScopeResult.prototype.hasItem = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional listenfield.BatchedQueryMetadata queryMeta = 2;
 * @return {?proto.listenfield.BatchedQueryMetadata}
 */
proto.listenfield.repo.QueryTimeScopeResult.prototype.getQuerymeta = function() {
  return /** @type{?proto.listenfield.BatchedQueryMetadata} */ (
    jspb.Message.getWrapperField(this, api_pb.BatchedQueryMetadata, 2));
};


/** @param {?proto.listenfield.BatchedQueryMetadata|undefined} value */
proto.listenfield.repo.QueryTimeScopeResult.prototype.setQuerymeta = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.listenfield.repo.QueryTimeScopeResult.oneofGroups_[0], value);
};


proto.listenfield.repo.QueryTimeScopeResult.prototype.clearQuerymeta = function() {
  this.setQuerymeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.listenfield.repo.QueryTimeScopeResult.prototype.hasQuerymeta = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.listenfield.repo);
